import thumbnail from './assets/thumbnail.jpg';

export const playlists = [
  {
    id: '1',
    name: 'Chill Mix',
    thumbnail: thumbnail,
    songs: [
      { id: '101', song: 'Sunset', artist: 'The xx', duraction: '03:39', link: thumbnail },
      { id: '102', song: 'Bloom', artist: 'ODESZA', duraction: '03:04', link: thumbnail },
      { id: '103', song: 'Intro', artist: 'alt-J', duraction: '02:37', link: thumbnail },
      { id: '410', song: 'Holocene', artist: 'Bon Iver', duraction: '05:43', link: thumbnail },
      { id: '411', song: 'Perth', artist: 'Bon Iver', duraction: '04:22', link: thumbnail },
      { id: '412', song: 'Blood Bank', artist: 'Bon Iver', duraction: '04:45', link: thumbnail },
      { id: '413', song: 'To Build A Home', artist: 'The Cinematic Orchestra', duraction: '06:11', link: thumbnail },
      { id: '501', song: 'Starlight', artist: 'Muse', duraction: '03:59', link: thumbnail },
      { id: '502', song: 'Uprising', artist: 'Muse', duraction: '05:03', link: thumbnail },
      { id: '503', song: 'Plug In Baby', artist: 'Muse', duraction: '03:39', link: thumbnail },
    ],
  },
  {
    id: '2',
    name: 'Focus Flow',
    thumbnail: thumbnail,
    songs: [
        { id: '201', song: 'Music To Focus', artist: 'Concentration', duraction: '05:00', link: thumbnail },
        { id: '202', song: 'Study Beats', artist: 'Lo-fi Girl', duraction: '04:20', link: thumbnail },
        { id: '414', song: 'Arrival of the Birds', artist: 'The Cinematic Orchestra', duraction: '04:23', link: thumbnail },
        { id: '415', song: 'Heartbeats', artist: 'José González', duraction: '02:40', link: thumbnail }
    ],
  },
    {
    id: '3',
    name: 'Workout',
    thumbnail: thumbnail,
    songs: [
        { id: '301', song: 'Energy Boost', artist: 'Gym Hits', duraction: '03:10', link: thumbnail },
        { id: '401', song: 'Midnight City', artist: 'M83', duraction: '04:03', link: thumbnail },
        { id: '402', song: 'Shelter', artist: 'Porter Robinson & Madeon', duraction: '03:38', link: thumbnail },
        { id: '403', song: 'Innerbloom', artist: 'RÜFÜS DU SOL', duraction: '09:38', link: thumbnail },
        { id: '404', song: 'Tessellate', artist: 'alt-J', duraction: '03:02', link: thumbnail },
    ],
  },
];

export const songs = [
    { id: '101', song: 'Sunset', artist: 'The xx', duraction: '03:39', link: thumbnail },
    { id: '102', song: 'Bloom', artist: 'ODESZA', duraction: '03:04', link: thumbnail },
    { id: '103', song: 'Intro', artist: 'alt-J', duraction: '02:37', link: thumbnail },
    { id: '201', song: 'Music To Focus', artist: 'Concentration', duraction: '05:00', link: thumbnail },
    { id: '202', song: 'Study Beats', artist: 'Lo-fi Girl', duraction: '04:20', link: thumbnail },
    { id: '301', song: 'Energy Boost', artist: 'Gym Hits', duraction: '03:10', link: thumbnail },
    { id: '401', song: 'Midnight City', artist: 'M83', duraction: '04:03', link: thumbnail },
    { id: '402', song: 'Shelter', artist: 'Porter Robinson & Madeon', duraction: '03:38', link: thumbnail },
    { id: '403', song: 'Innerbloom', artist: 'RÜFÜS DU SOL', duraction: '09:38', link: thumbnail },
    { id: '404', song: 'Tessellate', artist: 'alt-J', duraction: '03:02', link: thumbnail },
    { id: '405', song: 'The Less I Know The Better', artist: 'Tame Impala', duraction: '03:38', link: thumbnail },
    { id: '406', song: 'New Person, Same Old Mistakes', artist: 'Tame Impala', duraction: '06:02', link: thumbnail },
    { id: '407', song: 'Reckoner', artist: 'Radiohead', duraction: '04:50', link: thumbnail },
    { id: '408', song: 'Nude', artist: 'Radiohead', duraction: '04:15', link: thumbnail },
    { id: '409', song: 'All I Need', artist: 'Radiohead', duraction: '03:49', link: thumbnail },
    { id: '410', song: 'Holocene', artist: 'Bon Iver', duraction: '05:43', link: thumbnail },
    { id: '411', song: 'Perth', artist: 'Bon Iver', duraction: '04:22', link: thumbnail },
    { id: '412', song: 'Blood Bank', artist: 'Bon Iver', duraction: '04:45', link: thumbnail },
    { id: '413', song: 'To Build A Home', artist: 'The Cinematic Orchestra', duraction: '06:11', link: thumbnail },
    { id: '414', song: 'Arrival of the Birds', artist: 'The Cinematic Orchestra', duraction: '04:23', link: thumbnail },
    { id: '415', song: 'Heartbeats', artist: 'José González', duraction: '02:40', link: thumbnail },
    { id: '416', song: 'Crosses', artist: 'José González', duraction: '02:43', link: thumbnail },
    { id: '417', song: 'Vesuvius', artist: 'Sufjan Stevens', duraction: '05:26', link: thumbnail },
    { id: '418', song: 'Chicago', artist: 'Sufjan Stevens', duraction: '06:04', link: thumbnail },
    { id: '419', song: 'Casimir Pulaski Day', artist: 'Sufjan Stevens', duraction: '05:53', link: thumbnail },
    { id: '420', song: 'Such Great Heights', artist: 'The Postal Service', duraction: '04:26', link: thumbnail },
    { id: '421', song: 'The District Sleeps Alone Tonight', artist: 'The Postal Service', duraction: '04:44', link: thumbnail },
    { id: '501', song: 'Starlight', artist: 'Muse', duraction: '03:59', link: thumbnail },
    { id: '502', song: 'Uprising', artist: 'Muse', duraction: '05:03', link: thumbnail },
    { id: '503', song: 'Plug In Baby', artist: 'Muse', duraction: '03:39', link: thumbnail },
    { id: '504', song: 'Knights of Cydonia', artist: 'Muse', duraction: '06:07', link: thumbnail },
    { id: '505', song: 'Hysteria', artist: 'Muse', duraction: '03:47', link: thumbnail },
    { id: '506', song: 'Feeling Good', artist: 'Muse', duraction: '03:19', link: thumbnail },
    { id: '507', song: 'Madness', artist: 'Muse', duraction: '04:39', link: thumbnail },
    { id: '508', song: 'Survival', artist: 'Muse', duraction: '05:47', link: thumbnail },
    { id: '509', song: 'The 2nd Law: Unsustainable', artist: 'Muse', duraction: '03:47', link: thumbnail },
    { id: '510', song: 'Panic Station', artist: 'Muse', duraction: '03:03', link: thumbnail },
    { id: '511', song: 'Supermassive Black Hole', artist: 'Muse', duraction: '03:29', link: thumbnail },
    { id: '512', song: 'Time Is Running Out', artist: 'Muse', duraction: '03:56', link: thumbnail },
    { id: '513', song: 'Absolution', artist: 'Muse', duraction: '04:59', link: thumbnail },
    { id: '514', song: 'Pressure', artist: 'Muse', duraction: '03:55', link: thumbnail },
    { id: '515', song: 'Thought Contagion', artist: 'Muse', duraction: '03:26', link: thumbnail },
    { id: '516', song: 'Dig Down', artist: 'Muse', duraction: '03:48', link: thumbnail },
    { id: '517', song: 'Something Human', artist: 'Muse', duraction: '03:46', link: thumbnail },
    { id: '518', song: 'Algorithm', artist: 'Muse', duraction: '04:23', link: thumbnail },
    { id: '519', song: 'The Dark Side', artist: 'Muse', duraction: '03:47', link: thumbnail },
    { id: '520', song: 'Break It To Me', artist: 'Muse', duraction: '03:37', link: thumbnail },
    { id: '521', song: 'Propaganda', artist: 'Muse', duraction: '03:00', link: thumbnail },
    { id: '522', song: 'Mercy', duraction: '03:51', link: thumbnail },
    { id: '523', song: 'Psycho', artist: 'Muse', duraction: '05:28', link: thumbnail },
    { id: '524', song: 'Dead Inside', artist: 'Muse', duraction: '04:22', link: thumbnail }
];
